%YAML 1.2
---

n_runs: 100

graphical: True

log_level: warn

agent_type: GreedyAgent #Random GreedyAgent

map_size: 10

max_number_of_seeds: 10

max_battery_capacity: 100

Random:
  nr_charging_stations: 1
  nr_agents: 2

GreedyAgent:
  nr_charging_stations: 1
  nr_agents: 5